#!/usr/bin/env bash

#------------------------------------------------------------------------------
# append to prompt: user@host or user or root@host
# arg: $1 foreground color
# arg: $2 background color
# option variables;
#   PL_USER_SHOW_HOST: true/false to show host name/ip
#   PL_USER_USE_IP: true/false to show IP instead of hostname
function userhost_segment {
  local bg_color="$1"
  local fg_color="$2"
  local sshbg_color="$3"
  local sshfg_color="$4"

  # Show host if true or when user is remote/root
  if [[ "${SSH_CLIENT}" || "${SSH_TTY}" ]]; then
    local content="歷\u"
    if [ "$PL_SSH_SHOW_HOST" = true ]; then
      if [ "$PL_SSH_USE_IP" = true ]; then
        content+="@$(ip_address)"
      else
        content+="@\h"
      fi
    fi
    PS1+="$(segment_end "$sshfg_color" "$sshbg_color")"
    PS1+="$(segment_content "$sshfg_color" "$sshbg_color" " $content ")"
    __last_color="$sshbg_color"
  else
    local content="\u"
    if [ "$PL_USER_SHOW_HOST" = true ]; then
      if [ "$PL_USER_USE_IP" = true ]; then
        content+="@$(ip_address)"
      else
        content+="@\h"
      fi
    fi
    PS1+="$(segment_end "$fg_color" "$bg_color")"
    PS1+="$(segment_content "$fg_color" "$bg_color" " $content ")"
    __last_color="$bg_color"
  fi
}
